### PR TITLE
Fix broken link to Installation Guide

### PR DESCRIPTION
**Pull request by CruciformHawk7**

### CODE REVIEW

**Comment by CruciformHawk7** [comment]
Hello, the link seems to work, though. Will you test it again, please?
https://github.com/sodafoundation/documentation/blob/1dcd52e4bd63e641f728e8c8bd1747411b2e06d5/content/try-opensds/quickstart.md

**Comment by anvithks** [comment]
Hey @CruciformHawk7. 
The documentation website is deployed using netlify and developed with Hugo generator. 
The  .md files in the content folder serve as the source. The deploy preview is generated when a PR is raised and the site is deployed. 
You can check the deploy preview by clicking on the link [here] (https://deploy-preview-33--soda-docs.netlify.com/)

**Comment by anvithks** [comment]
You can check out this deploy preview by scrolling down to the `All checks have passed ` section and click on the deploy-preview link.

**Comment by CruciformHawk7** [comment]
That fixes the website, but the docs (from GitHub) is still broken. is this intentional?

**Comment by anvithks** [comment]
Yes. The docs are viewed only using the website docs.sodafoundation.io

**Comment by CruciformHawk7** [comment]
Thank you, I have fixed the link. https://deploy-preview-33--soda-docs.netlify.com/try-opensds/quickstart/

**Pull request merged**
