### PR TITLE
Update documentation quick start guide for Jerba release

### PR DESCRIPTION
**Pull request by joseph-v**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind new feature
> /kind bug fix
> /kind cleanup
> /kind revert change
> /kind design
> /kind documentation
> /kind enhancement

**What this PR does / why we need it**:
Update documentation quick start guide for Jerba release

**Which issue(s) this PR fixes**:

Fixes #

**Test Report Added?**:
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
> /kind TESTED
> /kind NOT-TESTED

**Test Report**:

**Special notes for your reviewer**:

### CODE REVIEW

**Review by kumarashit — APPROVED** [review]
LGTM

**Review by rajat-soda — APPROVED** [review]
LGTM

**Review by anvithks — CHANGES_REQUESTED** [review]
As in the Ansible installation guide ubuntu 16.04 deprecation message needs to be added here and the steps specific to Ubuntu 16.04 must be removed. Please refer #176

**Review by anvithks — APPROVED** [review]
LGTM

**Pull request merged**
