### PR TITLE
Update Support Matrix for Delfin

### PR DESCRIPTION
**Pull request by amanr032**
What type of PR is this?
> /kind documentation

What this PR does / why we need it ?
Support Matrix update for Delfin

Which issue(s) this PR fixes
Documentation Fix
Added Support for below devices :
1. Dell EMC   -- ScaleIO
2. H3C           -- UniStor
3. MacroSAN -- MacroSAN
4. INSPUR     -- AS5500/AS5300/AS2600/AS2200
Fixes #

**Test Report Added?**:
> /kind TESTED
> /kind NOT-TESTED

Test Report:

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by anvithks** [comment]
@amanr032 Please add what was updated in the support matrix in the description. It is difficult to make out what was changed in the file.

**Review by anvithks — DISMISSED** [review]
LGTM

**Comment by amanr032** [comment]
> @amanr032 Please add what was updated in the support matrix in the description. It is difficult to make out what was changed in the file.

Updated

**Review by anvithks — APPROVED** [review]
LGTM

**Review by joseph-v — APPROVED** [review]
LGTM

**Pull request merged**
