### PR TITLE
Added shortcode to support embedding pdf files directly in the document.

### LINKED ISSUE #97: Use PDF embedding to attach original PDFs in API Spec page.
**Issue/Feature Description:**
Use PDF embedding to attach original PDFs in API Spec page.
Something on the lines of 
https://pdfobject.com/

**Why this issue to fixed / feature is needed(give scenarios or use cases):**
Original content should not be repeated in multiple places. It increases maintenance effort. 

**How to reproduce, in case of a bug:**
NA
**Other Notes /  Environment Information: (Please give the env information, log link or any useful information for this issue)**
 NA

@anvithks Please look into this.

### PR DESCRIPTION
**Pull request by anvithks**
**What type of PR is this?**
/kind enhancement

**What this PR does / why we need it**:
This PR adds the functionality to embed pdf files directly in the document. 
This is implemented using [pdf.js](https://mozilla.github.io/pdf.js/).

i have implemented a custom shortcode that allows the user to embed PDF files anywhere in the document.

**Usage:** 

`{{< embed-pdf url="path/to/file" >}}`

Currently supports local file embed. Absolute URL can be tested once the site is deployed as CORS needs to be enabled on the server.

**Which issue(s) this PR fixes**:
Fixes #97 

**Test Report Added?**:
/kind TESTED

**Test Report**:
embed-pdf

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by rajat-soda** [comment]
LGTM ..  
@kumarashit : I will close my PR , so the page will look like the original version ..with just the embedded page and to download the PDF , users can click the button .

**Comment by kumarashit** [comment]
@anvithks Huge changes. 
Is this because of Vendor code/files?

**Comment by anvithks** [comment]
> @anvithks Huge changes. 
> Is this because of Vendor code/files?

Yes. The static/js/pdf-js need not be reviewed.

**Comment by skdwriting** [comment]
@rajat-soda should we revert the architecture page? or update as needed. Please check

**Pull request merged**
