### PR TITLE
Fixed search not working issue on SODA Documentation

### LINKED ISSUE #257: Search not working proper at https://docs.sodafoundation.io/
**Issue/Feature Description:**
Currently the search button shows only the current page search results highlighted. Not search in side the document pages.

**Why this issue to fixed / feature is needed(give scenarios or use cases):**
To get proper search results and find relevant documents faster

**How to reproduce, in case of a bug:**
Got to https://docs.sodafoundation.io/ and left side search button enter any keyword to search.

**Other Notes /  Environment Information: (Please give the env information, log link or any useful information for this issue)**
NA

### PR DESCRIPTION
**Pull request by ravisaxena23**
**What type of PR is this?**
/kind bug fix

**What this PR does / why we need it**:
To get proper search results and find relevant documents faster

**Which issue(s) this PR fixes**:
Fixes #257 

**Test Report Added?**:
/kind NOT-TESTED

**Test Report**:

**Special notes for your reviewer**:

### CODE REVIEW

**Review by anvithks — APPROVED** [review]
LGTM

Thanks @ravisaxena23

**Comment by anvithks** [comment]
@skdwriting Seems like this fixed the issue. Please check the deploy preview.

**Review by anvithks — CHANGES_REQUESTED** [review]
Just rechecked and seems like the commit message is incorrect. PLease check

**Comment by ravisaxena23** [comment]
I am closing it due to incorrect msg will re raise again

**Pull request closed without merging**
