### PR TITLE
Update the currently supported vendors in user guide of dashboard in …

### PR DESCRIPTION
**Pull request by shelar1423**
…delfin documentation #844

#192 
Updated currently supported vendors in user guide of dashboard in delfin doucmentation in regards with the setup.py drivers information available .

### CODE REVIEW

**Comment by shelar1423** [comment]
@anvithks @joseph-v kindly label sodacode2022 nd sodalow

**Comment by anvithks** [comment]
@shelar1423 This is a duplicate of #193 which already has one approval. 
#SODA-PR-Accepted

**Comment by shelar1423** [comment]
@anvithks but it's reopened by @joseph-v ?

**Comment by anvithks** [comment]
> @anvithks but it's reopened by @joseph-v ?

The issue is not yet closed. There is already a PR (#193 ) with the same solution that has one approval. 
This PR will be redundant once that PR is merged.

**Comment by anvithks** [comment]
Closing since duplicate of #193 which is merged.

**Pull request closed without merging**
