### PR TITLE
Add description and project links to introduction page

### PR DESCRIPTION
**Pull request by rajat-soda**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
 /kind documentation

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #88 

**Test Report Added?**:
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
> /kind TESTED
> /kind NOT-TESTED

**Test Report**:

Docs-Issue-89

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by rajat-soda** [comment]
@anvithks @kumarashit Please review

**Review by anvithks — CHANGES_REQUESTED** [review]
in the documentation website using #, ##, ### and so on adds the respective heading to the page naigation menu. The page navigation menu.

image
 
image

Every ## is added as  a top level menu item and subsequent ### will be added as a sub navigation.

So, for highlighting a line or marking important points   we can use bold (** **) and for titles / sub titles we can use the ##

**Comment by anvithks** [comment]
LGTM

**Review by anvithks — APPROVED** [review]
LGTM

**Review by kumarashit — APPROVED** [review]
LGTM

**Pull request merged**
