### PR TITLE
Add EmbedPDF  shortcode to embed pdfs

### LINKED ISSUE #93: Add details to SODA API Specification page.
**Issue/Feature Description:**
The Page is blank , with only one link, It will be good add basic details in the page. 

**Why this issue to fixed / feature is needed(give scenarios or use cases):**
Page is blank .

**How to reproduce, in case of a bug:**
NA
**Other Notes /  Environment Information: (Please give the env information, log link or any useful information for this issue)**
NA

### PR DESCRIPTION
**Pull request by rajat-soda**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
 /kind new feature

**What this PR does / why we need it**:
PR Adds EmbedPDF  shortcode to embed pdfs in docs.sodafoundation.io

**Which issue(s) this PR fixes**:

Fixes #93 

**Test Report Added?**:
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line: /kind TESTED

**Test Report**:

image

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by rajat-soda** [comment]
@anvithks @kumarashit  Please review and merge. 
- Removed the content that can change .
- Embedded the Original PDF itself on the page. 
This way the page is no more just a link, and provides readers with some overview of the API Specification and the Original DOC aswell. 
 Hope it addresses all the concerns discussed earlier.

**Review by anvithks — APPROVED** [review]
LGTM

**Comment by anvithks** [comment]
@kumarashit Please review and merge.

**Review by kumarashit — APPROVED** [review]
LGTM

**Pull request merged**
