### PR TITLE
Added Faroe release to docs.sodafoundation.io

### LINKED ISSUE #73: Releases Section Page can be improved
**Issue/Feature Description:**
docs.sodafoundation.io
https://docs.sodafoundation.io/releases/ can be improved with consistent data. We can simply link to the release pages of the projects? Or one of the release notes? Do we need to give the description repeated on this page?

**Why this issue to fixed / feature is needed(give scenarios or use cases):**
Improve the documentation

**How to reproduce, in case of a bug:**
NA

**Other Notes /  Environment Information: (Please give the env information, log link or any useful information for this issue)**
NA

### PR DESCRIPTION
**Pull request by rajat-soda**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind new feature
> /kind bug fix
> /kind cleanup
> /kind revert change
> /kind design
/kind documentation
> /kind enhancement

**What this PR does / why we need it**:
Added Faroe release to the documentation 

**Which issue(s) this PR fixes**:

Fixes #73 

**Test Report Added?**:
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
/kind TESTED
> /kind NOT-TESTED

**Test Report**:

image

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by rajat-soda** [comment]
@skdwriting @kumarashit @anvithks  : Please review .

**Review by anvithks — APPROVED** [review]
LGTM.
@skdwriting @kumarashit Having just the one line in this page and that too linking to external page is not ideal. 
We can have some content here with the highlights of the release and link to the release page for using the release. It will make it easier for the user to read about all the releases at one place.
Something like this [OpenEBS release docs](https://docs.openebs.io/docs/next/releases.html) 
We do not have a right menu but we could have a singe releases page format with the key improvements, bug fixes and any known issues.
let me know what you think.

**Comment by anvithks** [comment]
@rajat-soda Thanks for this and congratulations on your first PR to SODA :partying_face:

**Review by kumarashit — APPROVED** [review]
LGTM

**Comment by kumarashit** [comment]
@anvithks yes, you are right. we can pull in the content from github.com/release to here. @rajat-soda, Please check

**Pull request merged**
